"use strict"

const path = require("path")
const {translationTypes} = require("./translation-type-utils")
const {includesCustom, includesDefault} = require("./translation-type-utils")

/**
 * Returns the name of the Elm module to use for a file at the supplied path. e.g. for `"Translations/Greetings.elm"` the
 * returned value is `"Translations.Greetings"`.
 */
const moduleNameFromPath = filePath => {
    const {dir, name} = path.parse(filePath)
    const dirParts = dir.split(path.sep).filter(s => !!s)
    return dirParts.length
        ? dirParts.join(".") + "." + name
        : name
}

/**
 * Returns the path to use for a file containing the code for the passed in module. e.g. for `"Translations.Greetings"` the
 * returned value is `"Translations/Greetings.elm"`.
 */
const pathFromModuleName = moduleName => moduleName.replace(/\./g, path.sep) + ".elm"

/**
 * Returns an array of items to import from the I18Next module.
 */
const getExposings = (useFallbackLanguages, translationType) => {
    const types = ["Delims(..)", "Translations"]
    const defaultFunctions = useFallbackLanguages ? ["tf", "trf"] : ["t", "tr"]
    const customFunctions = useFallbackLanguages ? ["customTrf"] : ["customTr"]

    const functions = []
    // Use custom functions first as they come first in alphabetical order, and elm-format will sort them alphabetically.
    if (includesCustom(translationType)) functions.push(...customFunctions)
    if (includesDefault(translationType)) functions.push(...defaultFunctions)

    return [...types, ...functions].join(", ")
}
/**
 * Builds up the start of the code for a module with the passed in name.
 */
const buildFileStart = (moduleName, useFallbackLanguages = false, translationType = translationTypes.default) =>
    `-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module ${moduleName} exposing (..)

import I18Next exposing (${getExposings(useFallbackLanguages, translationType)})
`

module.exports = {
    moduleNameFromPath,
    pathFromModuleName,
    buildFileStart
}
