"use strict"

const path = require("path")

/**
 * Returns the name of the Elm module to use for a file at the supplied path. e.g. for `"Translations/Greetings.elm"` the
 * returned value is `"Translations.Greetings"`.
 */
const moduleNameFromPath = filePath => {
    const {dir, name} = path.parse(filePath)
    const dirParts = dir.split(path.sep).filter(s => !!s)
    return dirParts.length
        ? dirParts.join(".") + "." + name
        : name
}

/**
 * Returns the path to use for a file containing the code for the passed in module. e.g. for `"Translations.Greetings"` the
 * returned value is `"Translations/Greetings.elm"`.
 */
const pathFromModuleName = moduleName => moduleName.replace(/\./g, path.sep) + ".elm"

/**
 * Builds up the start of the code for a module with the passed in name.
 */
const buildFileStart = (moduleName, useFallbackLanguages = false) =>
    `-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module ${moduleName} exposing (..)

import I18Next exposing (Delims(..), Translations, ${useFallbackLanguages ? "tf, trf" : "t, tr"})
`

module.exports = {
    moduleNameFromPath,
    pathFromModuleName,
    buildFileStart
}